### PR TITLE
Mainnet Staking Event Coverage

### PR DESCRIPTION
**Pull request by GundamDweeb**
Split out the Mainnet Changes from the updates made in #30

### CODE REVIEW

**Comment by GundamDweeb** [comment]
https://thegraph.com/hosted-service/subgraph/gundamdweeb/nftx-v2

**Comment by GundamDweeb** [comment]
- Includes Withdraw & Deposit events.
- Blockhandlers have been removed. 
- 
_Javery Deposit Query_
**Staking vToken to xToken for POGGER** - https://etherscan.io/tx/0x403c179dd0ef12c33fb02477fa0a8f5ae18e2dbe9795a14e72eabc9a40475992 

_Javery Withdraw Query_
**unstake liquidity** : https://etherscan.io/tx/0x3b545e46a762a91e5269770a8333869b78b4fec39039c43b54d537f999c08dbd

_Javery Deposit 2 Query_
**stake liquidity:** https://etherscan.io/tx/0x8d1065a2719ef2fe5a09c3475aa093d656512eba52c54075bebb3bcfae016643

_Javery Withdrawal 2 Query_
**Unstake Inventory to Token:** https://etherscan.io/tx/0x8e67bb823ee748b56c47b2f9b75199c5d811c5c95c14c0b038b08aa27df26ceb

See subgraph for queries :
https://thegraph.com/hosted-service/subgraph/gundamdweeb/nftx-v2

**Comment by justincavery** [comment]
@GundamDweeb Are we able to merge these changes in with the updates to the 0xMarketplace as well when deploying to main?

**Comment by GundamDweeb** [comment]
Work has been implemented in #30

**Pull request closed without merging**
